services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./app:/var/www/html:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - /dev/shm:/dev/shm